### ISSUE TITLE
Error when running ./sbt: [error] (FoBo-Demo/*:update) sbt.ResolveException: unresolved dependency: net.liftmodules#fobo_2.6_2.11;1.4-SNAPSHOT: not found

### ISSUE THREAD

**Issue by shafiquejamal** [karma4u101/FoBo-Demo#3]
Hello,

I cloned this repo, and ran the ./sbt command - this resulted in the following error:

```
info] Resolving net.liftmodules#fobo_2.6_2.11;1.4-SNAPSHOT ...
[warn] 	module not found: net.liftmodules#fobo_2.6_2.11;1.4-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/shafiquejamal/.ivy2/local/net.liftmodules/fobo_2.6_2.11/1.4-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/net/liftmodules/fobo_2.6_2.11/1.4-SNAPSHOT/fobo_2.6_2.11-1.4-SNAPSHOT.pom
[warn] ==== snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/net/liftmodules/fobo_2.6_2.11/1.4-SNAPSHOT/fobo_2.6_2.11-1.4-SNAPSHOT.pom
[warn] ==== staging: tried
[warn]   https://oss.sonatype.org/content/repositories/staging/net/liftmodules/fobo_2.6_2.11/1.4-SNAPSHOT/fobo_2.6_2.11-1.4-SNAPSHOT.pom
[warn] ==== releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/net/liftmodules/fobo_2.6_2.11/1.4-SNAPSHOT/fobo_2.6_2.11-1.4-SNAPSHOT.pom
[info] Resolving jline#jline;2.12 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: net.liftmodules#fobo_2.6_2.11;1.4-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: net.liftmodules#fobo_2.6_2.11;1.4-SNAPSHOT: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:213)
...
	at java.lang.Thread.run(Thread.java:745)
[error] (FoBo-Demo/*:update) sbt.ResolveException: unresolved dependency: net.liftmodules#fobo_2.6_2.11;1.4-SNAPSHOT: not found
```

Would you have any suggestions on how to fix this? 

Thanks,

**Comment by karma4u101** [comment]
Ah yes didn't thing about that I have published 1.4 and there is now a 1.5-SNAPSHOT dependency in one of the demo sub projects. I will update

**Comment by karma4u101** [comment]
Its updated now so try it out.

**Comment by shafiquejamal** [comment]
Thanks! That error is now gone. However, now in SBT when I type "container:start" I get the following error:
```
trace] Stack trace suppressed: run last FoBo-Demo/container:start for the full output.
[error] (FoBo-Demo/container:start) java.lang.IllegalArgumentException: file:/path/to/FoBo-Demo/src/main/webapp is not an existing directory.
```

Any advice? Thanks,

**Comment by karma4u101** [comment]
Yes this is a "multi project" project so you have to navigate down to one of its sub folders to start a demo app, for example the pimping-lift_advanced_bs3 or the pimping-lift_advanced_md (the later is work in progress) you can do that by ether start sbt from one of the included subfolders or you can start at the root (as you did above) and use the sbt command 'projects' to list all the sub projects and then use the command 'project <projectName>' to navigate into the project and then use container:start, container:stop to start and stop the demo app.  Hope that helps

**Comment by shafiquejamal** [comment]
Ah, I see. Yep - all is good now, thanks!
